### ISSUE TITLE
New rule suggestion: Replace `in order for` with `for`

### ISSUE THREAD

**Issue by katydecorah** [retextjs/retext-simplify#11]
### Subject of the feature

Similar to the rule:

> Replace `in order to` with `to` 

I'd like to recommend a rule to catch the phrase `in order for`:

> Replace `in order for` with `for`

I'd be happy to PR if this seems like a good addition.

**Comment by wooorm** [comment]
That’s a great suggestion, Katy, yeah! PR would be welcome! Otherwise I’ll get to it somewhere in the coming months
