### ISSUE TITLE
`has no effect` triggers a warning with no suitable alternative.

### ISSUE THREAD

**Issue by aduh95** [retextjs/retext-simplify#13]
### Initial checklist

- [ ] I read the [support docs](https://github.com/retextjs/.github/blob/main/support.md)
- [ ] I read the [contributing guide](https://github.com/retextjs/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/retextjs/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Aretextjs&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

The following sentence:

```markdown
If the [`formData`](#formData-true) option is set to false, `metaFields` has no effect.
```

Produces the following result:

```
warning   Replace `effect` with `choose`, `pick`
```

None of the suggested alternative works here.

### Solution

Either provide a different alternative, or accept `has no effect` as a valid expression.

### Alternatives

Add `'effect'` to the ignore list.

**Comment by wooorm** [comment]
It’s a pretty simple module, there is no awareness of context, so accepting one word in certain combinations is not possible.

Some alternatives:

- `does nothing` or `does not apply` (this matches your context but can’t be added to suggestions)
- `has no result` (`result` could be added to the list of suggestions)
- `` `metaFields` does nothing/not apply when `formData` is set to `false` `` (rewrite sentence)

**Comment by aduh95** [comment]
Maybe we could do something similar to `benefit` to provide more granular suggestion based on a combination of words: https://github.com/retextjs/retext-simplify/blob/60e019306e3813af87bdee28ee4b632fce5ee46a/patterns.js#L194-L199

I haven't tried it, but maybe something like that would work:
```js
  'has no effect': { replace: ['does nothing', 'does not apply'] },
```

+1 for adding `result` to the list of suggestions, do you want me to open a PR?

In any case, thanks for your helpful suggestions – and for this plugin, it's quite helpful for someone like me who is not English native speaker.

**Comment by wooorm** [comment]
oh that’s interesting, I don’t remember that `benefit from` technique.

Yes, PR would be great! With either or both of the `'has no effect'` and `result` in `effect` cases?

> In any case, thanks for your helpful suggestions – and for this plugin, it's quite helpful for someone like me who is not English native speaker.

Good to hear, thanks! :+1:
